/**:
  ros__parameters:
    robots:
    - agent: jackal_marl
      amount: 2
      model: jackal
      planner: rosnav
    - agent: rto_marl
      amount: 2
      model: rto
      planner: rosnav
    - agent: ridgeback_marl
      amount: 2
      model: ridgeback
      planner: rosnav
