/**:
  ros__parameters:
    joy_node:
      autorepeat_rate: 20
      deadzone: 0.1
      dev: /dev/input/js0
    teleop_twist_joy:
      axis_angular:
        yaw: 3
      axis_linear:
        x: 1
        y: 0
      enable_button: 10
      enable_turbo_button: 8
      scale_angular:
        yaw: 0.5
      scale_linear:
        x: 0.4
        y: 0.4
