/**:
  ros__parameters:
    joint_limits:
      wheel_left_joint:
        has_acceleration_limits: true
        max_acceleration: 10.0
      wheel_right_joint:
        has_acceleration_limits: true
        max_acceleration: 10.0
