DwaLocalPlannerROS:

  # params are from https://github.com/dietriro/rto_core/tree/noetic-devel/rto_navigation/config
  # and https://www.robotshop.com/media/files/content/f/fto/pdf/festo-robotino-mobile-robotic-datasheet.pdf

  # Robot Configuration Parameters
  max_vel_x: 2.78
  min_vel_x: -2.78

  max_vel_y: 2.78
  min_vel_y: -2.78

  # The velocity when robot is moving in a straight line
  max_vel_trans: 2.78
  min_vel_trans: 1.39

  max_vel_theta: 1.0
  min_vel_theta: 0.5

  acc_lim_x: 2.5
  acc_lim_theta: 3.2

  # Goal Tolerance Parametes
