/**:
  ros__parameters:
    footprint:
    - - -0.105
      - -0.105
    - - -0.105
      - 0.105
    - - 0.041
      - 0.105
    - - 0.041
      - -0.105
    observation_sources: scan
    robot_base_frame: $(arg frame)base_footprint
    robot_radius: 0.275
    scan:
      clearing: true
      data_type: LaserScan
      marking: true
      sensor_frame: $(arg frame)base_laser_link
      topic: $(arg namespace)/scan
