/**:
  ros__parameters:
    additionalArguments:
    - name: trainings_environment
      value: rosnav
    - name: network_type
      value: rosnav
    local_planner: rosnav
    scenarios:
    - map_files:
      - map_file: small_warehouse
        scenario: eval_mar_2022/small_warehouse_obs05.json
      - map_file: map2
        scenario: eval_mar_2022/map2_obs05.json
      - map_file: map5
        scenario: eval_mar_2022/map5_obs05.json
      robot: burger
    - map_files:
      - map_file: small_warehouse
        scenario: eval_mar_2022/small_warehouse_obs05.json
      - map_file: map2
        scenario: eval_mar_2022/map2_obs05.json
      - map_file: map5
        scenario: eval_mar_2022/map5_obs05.json
      - map_file: small_warehouse
        scenario: eval_mar_2022/small_warehouse_obs10.json
      - map_file: map2
        scenario: eval_mar_2022/map2_obs10.json
      - map_file: map5
        scenario: eval_mar_2022/map5_obs10.json
      robot: jackal
    - map_files:
      - map_file: small_warehouse
        scenario: eval_mar_2022/small_warehouse_obs05.json
      - map_file: map2
        scenario: eval_mar_2022/map2_obs05.json
      - map_file: map5
        scenario: eval_mar_2022/map5_obs05.json
      - map_file: small_warehouse
        scenario: eval_mar_2022/small_warehouse_obs10.json
      - map_file: map2
        scenario: eval_mar_2022/map2_obs10.json
      - map_file: map5
        scenario: eval_mar_2022/map5_obs10.json
      robot: youbot
