robot_base_frame: $(arg frame)base_footprint

# footprint: [[-0.21, -0.21], [-0.21, 0.21], [0.21, 0.21], [0.21, -0.21]]
footprint: [[-0.285, 0.285], [-0.285, -0.285], [0.285, -0.285], [0.285, 0.285]]
robot_radius: 0.755

inscribed_radius: 0.755
circumscribed_radius: 0.755

observation_sources: scan
scan:
  {
    sensor_frame: $(arg frame)base_laser_front_link,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,
  }


