/**:
  ros__parameters:
    default_actor_config:
      CHATTING_PROBABILITY:
      - 0.1
      - 0.25
      FORCE_FACTOR_DESIRED:
      - 1
      - 5
      FORCE_FACTOR_OBSTACLE:
      - 1
      - 7
      FORCE_FACTOR_ROBOT:
      - 2
      - 10
      FORCE_FACTOR_SOCIAL:
      - 5
      - 8
      GROUP_TALKING_PROBABILITY:
      - 0.15
      - 0.25
      MAX_TALKING_DISTANCE: 1
      TALKING_AND_WALKING_PROBABILITY: 0
      TALKING_BASE_TIME: 5
      TELL_STORY_BASE_TIME: 5
      TELL_STORY_PROBABILITY:
      - 0.05
      - 0.15
      VMAX:
      - 0.3
      - 0.5
      WAYPOINT_MODE: 1
