/**:
  ros__parameters:
    additionalArguments:
    - name: trainings_environment
      value: rosnav
    - name: network_type
      value: rosnav
    local_planner: rosnav
    scenarios:
    - map_files:
      - map_file: ignc
        scenario: eval_feb_2022/ignc_obs05.json
      robot: turtlebot3_burger
    - map_files:
      - map_file: ignc
        scenario: eval_feb_2022/ignc_obs05.json
      robot: rto
    - map_files:
      - map_file: ignc
        scenario: eval_feb_2022/ignc_obs05.json
      robot: jackal
    - map_files:
      - map_file: ignc
        scenario: eval_feb_2022/ignc_obs05.json
      robot: youbot
