/**:
  ros__parameters:
    actions:
      continuous:
        angular_range:
        - -2.0
        - 2.0
        linear_range:
        - -1.5
        - 1.5
      discrete:
      - angular: 0.0
        linear: 1.5
        name: move_forward
      - angular: 0.0
        linear: -0.15
        name: move_backward
      - angular: 0.35
        linear: 0.15
        name: turn_left
      - angular: -0.35
        linear: 0.15
        name: turn_right
      - angular: 0.75
        linear: 0.0
        name: turn_strong_left
      - angular: -0.75
        linear: 0.0
        name: turn_strong_right
      - angular: 0.0
        linear: 0.0
        name: stop
    is_holonomic: false
    laser:
      angle:
        increment: 0.00533294445
        max: 1.9198600053787231
        min: -1.9198600053787231
      num_beams: 666
      range: 25.0
      update_rate: 10
    robot_base_frame: base_footprint
    robot_model: tiago
    robot_radius: 0.27
    robot_sensor_frame: base_laser_link
