/**:
  ros__parameters:
    arm_impedance_controller:
      constraints:
        arm_1_joint:
          goal: 0.02
        arm_2_joint:
          goal: 0.02
        arm_3_joint:
          goal: 0.02
        arm_4_joint:
          goal: 0.02
        arm_5_joint:
          goal: 0.02
        arm_6_joint:
          goal: 0.02
        arm_7_joint:
          goal: 0.02
        goal_time: 0.6
        stopped_velocity_tolerance: 5.0
      impedance_gains:
        arm_1_joint:
          kd: 1.0
          kp: 6.0
        arm_2_joint:
          kd: 0.8
          kp: 6.0
        arm_3_joint:
          kd: -0.8
          kp: -6.0
        arm_4_joint:
          kd: -0.8
          kp: -6.0
        arm_5_joint:
          kd: -0.02
          kp: -0.02
        arm_6_joint:
          kd: 0.02
          kp: 0.2
        arm_7_joint:
          kd: 0.2
          kp: 0.2
      joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
      motor_params:
        arm_1_joint:
          motor_torque_constant: 0.0
          reduction_ratio: 100.0
        arm_2_joint:
          motor_torque_constant: 0.136
          reduction_ratio: 100.0
        arm_3_joint:
          motor_torque_constant: -0.087
          reduction_ratio: 100.0
        arm_4_joint:
          motor_torque_constant: -0.087
          reduction_ratio: 100.0
        arm_5_joint:
          motor_torque_constant: 0.0
          reduction_ratio: 336.0
        arm_6_joint:
          motor_torque_constant: 0.0
          reduction_ratio: 336.0
        arm_7_joint:
          motor_torque_constant: 0.0
          reduction_ratio: 336.0
      robot_model_chains:
      - gripper_link
      type: impedance_controllers/JointTrajectoryController
