/**:
  ros__parameters:
    gripper_controller:
      constraints:
        goal_time: 0.6
        gripper_left_finger_joint:
          goal: 0.02
        gripper_right_finger_joint:
          goal: 0.02
        stopped_velocity_tolerance: 5.0
      joints:
      - gripper_right_finger_joint
      - gripper_left_finger_joint
      type: position_controllers/JointTrajectoryController
