/**:
  ros__parameters:
    gripper_controller:
      constraints:
        goal_time: 0.6
        gripper_finger_joint:
          goal: 0.02
        stopped_velocity_tolerance: 5.0
      joints:
      - gripper_finger_joint
      type: position_controllers/JointTrajectoryController
