/**:
  ros__parameters:
    teleop:
      move:
        axis_mappings:
        - axis: 1
          scale: 1.0
          target: linear.x
        - axis: 2
          scale: 1.0
          target: angular.z
        message_type: geometry_msgs/Twist
        topic_name: cmd_vel
        type: topic
