/**:
  ros__parameters:
    controller_params:
      static_friction_0: 0.5
      static_friction_1: 0.6
      static_friction_2: 0.8
      static_friction_3: 0.5
      torque_scaling_0: 1.0
      torque_scaling_1: 1.5
      torque_scaling_2: 1.0
      torque_scaling_3: 1.0
      viscous_friction_0: 2.1
      viscous_friction_1: 1.7
      viscous_friction_2: 2.3
      viscous_friction_3: 2.0
    gravity_compensation:
      base_link_name: base_link
      friction:
        arm_1_joint:
          s: 3.1
          v: 0.4
        arm_2_joint:
          s: 3.1
          v: 0.4
        arm_3_joint:
          s: 3.1
          v: 0.4
        arm_4_joint:
          s: 1.3
          v: 0.4
        arm_5_joint: &id001
          s: 0
          v: 0
        arm_6_joint: *id001
        arm_7_joint: *id001
        caster_back_left_1_joint: *id001
        caster_back_left_2_joint: *id001
        caster_back_right_1_joint: *id001
        caster_back_right_2_joint: *id001
        caster_front_left_1_joint: *id001
        caster_front_left_2_joint: *id001
        caster_front_right_1_joint: *id001
        caster_front_right_2_joint: *id001
        hand_index_abd_joint: *id001
        hand_index_flex_1_joint: *id001
        hand_index_flex_2_joint: *id001
        hand_index_flex_3_joint: *id001
        hand_index_joint: *id001
        hand_index_virtual_1_joint: *id001
        hand_index_virtual_2_joint: *id001
        hand_index_virtual_3_joint: *id001
        hand_little_abd_joint: *id001
        hand_little_flex_1_joint: *id001
        hand_little_flex_2_joint: *id001
        hand_little_flex_3_joint: *id001
        hand_little_virtual_1_joint: *id001
        hand_little_virtual_2_joint: *id001
        hand_little_virtual_3_joint: *id001
        hand_middle_abd_joint: *id001
        hand_middle_flex_1_joint: *id001
        hand_middle_flex_2_joint: *id001
        hand_middle_flex_3_joint: *id001
        hand_middle_virtual_1_joint: *id001
        hand_middle_virtual_2_joint: *id001
        hand_middle_virtual_3_joint: *id001
        hand_mrl_joint: *id001
        hand_ring_abd_joint: *id001
        hand_ring_flex_1_joint: *id001
        hand_ring_flex_2_joint: *id001
        hand_ring_flex_3_joint: *id001
        hand_ring_virtual_1_joint: *id001
        hand_ring_virtual_2_joint: *id001
        hand_ring_virtual_3_joint: *id001
        hand_thumb_abd_joint: *id001
        hand_thumb_flex_1_joint: *id001
        hand_thumb_flex_2_joint: *id001
        hand_thumb_joint: *id001
        hand_thumb_virtual_1_joint: *id001
        hand_thumb_virtual_2_joint: *id001
        head_1_joint: *id001
        head_2_joint: *id001
        torso_lift_joint: *id001
        wheel_left_joint: *id001
        wheel_right_joint: *id001
      hardware: true
      joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      reference_signal: circle
      tip_link_name: arm_7_link
      type: walking_force_control/GravityCompensation
    torque_constant:
      arm_1_joint: 0.0735
      arm_2_joint: 0.0735
      arm_3_joint: -0.1149
      arm_4_joint: -0.1149
      arm_5_joint: 0.0
      arm_6_joint: 0.0
      arm_7_joint: 0.0
    torque_control:
      base_link_name: base_link
      dt: 0.005
      hardware: true
      joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      reference_signal: circle
      tip_link_name: arm_7_link
      type: walking_force_control/ArmTorqueControlComand
    wrist_controller:
      constraints:
        arm_left_5_joint:
          goal: 0.02
        arm_left_6_joint:
          goal: 0.02
        arm_left_7_joint:
          goal: 0.02
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
      joints:
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
      type: position_controllers/JointTrajectoryController
    wrist_current_limit_controller:
      actuators:
      - arm_5_motor
      - arm_6_motor
      - arm_7_motor
      type: pal_ros_controllers/CurrentLimitController
