/**:
  ros__parameters:
    arm_controller:
      constraints:
        arm_1_joint:
          goal: 0.02
        arm_2_joint:
          goal: 0.02
        arm_3_joint:
          goal: 0.02
        arm_4_joint:
          goal: 0.02
        arm_5_joint:
          goal: 0.02
        arm_6_joint:
          goal: 0.02
        arm_7_joint:
          goal: 0.02
        goal_time: 0.6
        stopped_velocity_tolerance: 5.0
      joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
      type: position_controllers/JointTrajectoryController
    head_controller:
      constraints:
        goal_time: 2.0
        head_1_joint:
          goal: 0.02
        head_2_joint:
          goal: 0.02
        stopped_velocity_tolerance: 5.0
      joints:
      - head_1_joint
      - head_2_joint
      type: position_controllers/JointTrajectoryController
    torso_controller:
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 5.0
        torso_lift_joint:
          goal: 0.001
      joints:
      - torso_lift_joint
      type: position_controllers/JointTrajectoryController
