/**:
  ros__parameters:
    gripper_controller:
      gains:
        gripper_finger_joint_l:
          d: 1.0
          p: 1000.0
        gripper_finger_joint_r:
          d: 1.0
          p: 1000.0
      joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
      type: effort_controllers/JointTrajectoryController
