DwaLocalPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 1.1
  min_vel_x: -1.1

  max_vel_y: 1.1
  min_vel_y: -1.1

  # The velocity when robot is moving in a straight line
  max_vel_trans: 1.1
  min_vel_trans: 0.11

  max_vel_theta: 2.0
  min_vel_theta: 0.14

  acc_lim_x: 2.5
  acc_lim_theta: 1.0

  # Goal Tolerance Parametes
  sim_time: 2.0
  controller_frequency: 10.0

  # Trajectory Scoring Parameters
