# params are from https://github.com/ipa320/cob_navigation/tree/indigo_dev/cob_navigation_config/robots/cob4/nav/dwa_local_planner.yaml
# and https://www.care-o-bot.de/content/dam/careobot/de/documents/technischedaten/Care-O-bot%204_Technische_Daten.pdf
DwaLocalPlannerROS:
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  max_vel_x: 1.1 #default 0.3
  min_vel_x: -1.1 #default -0.3

  max_vel_y: 0.2 #increase like max_x?
  min_vel_y: -0.2

  max_trans_vel: 0.3
  min_trans_vel: 0.01

  max_rot_vel: 0.6
  min_rot_vel: 0.01

  #param for rotating behaviour
  #max_rotational_vel: 0.04
  #min_in_place_rotational_vel: 0.01


  sim_time: 1.7
  sim_granularity: 0.017

  goal_distance_bias: 32.0
  path_distance_bias: 24.0
  occdist_scale: 0.01

  forward_point_distance: 0.0

  vx_samples: 3
  vy_samples: 10
  vtheta_samples: 20

  sim_period: 0.1

  xy_goal_tolerance: 0.2 #0.3
  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01

  penalize_negative_x: false
