MpcLocalPlannerROS:
    ## Robot settings
  robot:
    type: unicycle
    unicycle:
      max_vel_x: 1.1
      max_vel_x_backwards: 1.1
      max_vel_theta: 0.8
      max_vel_y: 0.2
      acc_lim_x: 2.5 # deactive bounds with zero
      dec_lim_x: 2.5 # deactive bounds with zero
      acc_lim_y: 2.5
      acc_lim_theta: 0.8 # deactivate bounds with zero

  ## Footprint model for collision avoidance
  footprint_model:
    type: polygon
    vertices: [[0.4, 0.0], [0.35, 0.35], [-0.2, 0.4], [-0.45, 0.0], [-0.2, -0.4],
      [0.35, -0.35]]

  ## Planning grid
  grid:
    type: fd_grid
    variable_grid:
      enable: false # We want a fixed grid
  planning:
    objective:
      type: quadratic_form   # minimum_time requires grid/variable_grid/enable=True and grid/xf_fixed set properly
    terminal_cost:
      type: quadratic   # can be "none"
    terminal_constraint:
      type: none   # can be "none"
  solver:
    type: ipopt
    lsq_lm:
      iterations: 10
