TebLocalPlannerROS:

  # Trajectory

  max_samples: 500
  allow_init_with_backwards_motion: false
  max_global_plan_lookahead_dist: 29.5
  global_plan_viapoint_sep: -1
  global_plan_prune_distance: 1
  exact_arc_length: false
  publish_feedback: false

  # Robot

  max_vel_x: 1.1
  max_vel_x_backwards: 1.1
  max_vel_y: 0.2
  max_vel_theta: 0.8
  acc_lim_x: 2.5
  acc_lim_theta: 3.0
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

  footprint_model:
    type: point

  # GoalTolerance

