goal_reached:
  reward: 15

safe_distance:
  reward: -0.25

collision:
  reward: -15

approach_goal:
  pos_factor: 0.65
  neg_factor: 0.9
  _on_safe_dist_violation: true

reverse_drive:
  reward: -0.1
  _on_safe_dist_violation: true

approach_globalplan:
  pos_factor: 0.2
  neg_factor: 0.3
  _on_safe_dist_violation: false

two_factor_velocity_difference:
  alpha: 0.005
  beta: 0.01
  _on_safe_dist_violation: true

active_heading_direction:
  r_angle: 0.5
  iters: 60
  _on_safe_dist_violation: true

ped_type_collision:
  type: 1
  reward: -5

ped_type_safety_distance:
  type: 1
  reward: -0.1
  safety_distance: 0.5

# angular_vel_constraint:
#   penalty_factor: 0.05
#   threshold: 1.0