robot_base_frame: $(arg frame)base_link

footprint: [[0.48, -0.40], [0.48, 0.40], [-0.48, 0.40], [-0.48, -0.40]]
footprint_padding: 0.1

map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

publish_voxel_map: false
meter_scoring: true

observation_sources: scan
scan:
  {
    sensor_frame: $(arg frame)front_laser,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,
    min_obstacle_height: -2.0,
    max_obstacle_height: 2.0
  }