/**:
  ros__parameters:
    arm_controller:
      constraints:
        arm_joint_1:
          goal: 0.1
        arm_joint_2:
          goal: 0.1
        arm_joint_3:
          goal: 0.1
        arm_joint_4:
          goal: 0.1
        arm_joint_5:
          goal: 0.1
        goal_time: 0.6
      gains:
        arm_joint_1:
          d: 0.1
          i: 0.01
          p: 1000.0
        arm_joint_2:
          d: 0.1
          i: 0.01
          p: 1000.0
        arm_joint_3:
          d: 0.1
          i: 0.01
          p: 1000.0
        arm_joint_4:
          d: 0.1
          i: 0.01
          p: 1000.0
        arm_joint_5:
          d: 0.1
          i: 0.01
          p: 1000.0
      joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      type: effort_controllers/JointTrajectoryController
