/**:
  ros__parameters:
    base_controller:
      base_frame: base_footprint
      cmd_vel_timeout: 0.0
      linear_acceleration_limit: 2.5
      linear_deceleration_limit: 2.5
      linear_speed_limit: 1.5
      pid_gains:
        caster_joint_bl:
          d: 1.0
          i: 0.0
          p: 100.0
        caster_joint_br:
          d: 1.0
          i: 0.0
          p: 100.0
        caster_joint_fl:
          d: 1.0
          i: 0.0
          p: 100.0
        caster_joint_fr:
          d: 1.0
          i: 0.0
          p: 100.0
        wheel_joint_bl:
          d: 1.0
          i: 0.0
          p: 100.0
        wheel_joint_br:
          d: 1.0
          i: 0.0
          p: 100.0
        wheel_joint_fl:
          d: 1.0
          i: 0.0
          p: 100.0
        wheel_joint_fr:
          d: 1.0
          i: 0.0
          p: 100.0
      type: steered_wheel_base_controller/SteeredWheelBaseController
      wheels:
      - axle_joint: wheel_joint_fl
        diameter: 0.095
        steering_joint: caster_joint_fl
      - axle_joint: wheel_joint_fr
        diameter: 0.095
        steering_joint: caster_joint_fr
      - axle_joint: wheel_joint_bl
        diameter: 0.095
        steering_joint: caster_joint_bl
      - axle_joint: wheel_joint_br
        diameter: 0.095
        steering_joint: caster_joint_br
      yaw_acceleration_limit: 3.2
      yaw_deceleration_limit: 3.2
      yaw_speed_limit: 3.0
