/**:
  ros__parameters:
    abrupt_velocity_change:
      _on_safe_dist_violation: true
      vel_factors:
        '0': 0.3
        '1': 0.07
        '2': 0.07
    approach_globalplan:
      _on_safe_dist_violation: false
      neg_factor: 0.5
      pos_factor: 0.3
    approach_goal:
      _on_safe_dist_violation: true
      neg_factor: 0.6
      pos_factor: 0.5
    collision:
      reward: -10
    distance_travelled:
      _on_safe_dist_violation: false
      ang_vel_scalar: 0.001
      consumption_factor: 0.005
      lin_vel_scalar: 1.0
    follow_globalplan:
      _on_safe_dist_violation: false
      min_dist_to_path: 0.5
      reward_factor: 0.1
    goal_reached:
      reward: 15
    no_movement:
      _on_safe_dist_violation: true
      reward: -0.01
    reverse_drive:
      _on_safe_dist_violation: true
      reward: -0.0001
    safe_distance:
      reward: -0.2
