/**:
  ros__parameters:
    additionalArguments:
    - name: str
      value: str
    docker:
      dockerPath: str
      localPath: str
      name: str
    local_planner: str
    scenarios:
    - map_files:
      - map_file: str
        scenario: str
      robot: str
