/**:
  ros__parameters:
    additionalArguments:
    - name: trainings_environment
      value: dwa
    - name: network_type
      value: dwa
    local_planner: dwa
    scenarios:
    - map_files:
      - map_file: small_warehouse
        scenario: eval_feb_2022/eval_feb_2022/small_warehouse_obs05.json
      - map_file: ignc
        scenario: eval_feb_2022/eval_feb_2022/ignc_obs05.json
      robot: rto
