/**:
  ros__parameters:
    additionalArguments:
    - name: trainings_environment
      value: navrep
    - name: network_type
      value: rosnav
    docker:
      dockerPath: root/src/arena_local_planner_drl
      localPath: arena_navigation/arena_local_planer/learning_based/arena_local_planner_drl
      name: navrep
    local_planner: rosnav
    scenarios:
    - map_files:
      - map_file: small_warehouse
        scenario: eval_feb_2022/small_warehouse_obs05.json
      - map_file: ignc
        scenario: eval_feb_2022/ignc_obs05.json
      - map_file: map2
        scenario: eval_feb_2022/map2_obs05.json
      - map_file: map5
        scenario: eval_feb_2022/map5_obs05.json
      - map_file: small_warehouse
        scenario: eval_feb_2022/small_warehouse_obs10.json
      - map_file: ignc
        scenario: eval_feb_2022/ignc_obs10.json
      - map_file: map2
        scenario: eval_feb_2022/map2_obs10.json
      - map_file: map5
        scenario: eval_feb_2022/map5_obs10.json
      robot: rto
