/**:
  ros__parameters:
    chain_base_link: arm_podest_link
    chain_tip_link: arm_7_link
    frame_tracker:
      marker_scale: 0.3
      movable_rot: true
      movable_trans: true
      pid_rot_x:
        d: 0.0
        i: 0.0
        i_clamp: 0.0
        p: 4.0
      pid_rot_y:
        d: 0.0
        i: 0.0
        i_clamp: 0.0
        p: 4.0
      pid_rot_z:
        d: 0.0
        i: 0.0
        i_clamp: 0.0
        p: 4.0
      pid_trans_x:
        d: 0.0
        i: 0.0
        i_clamp: 0.0
        p: 4.0
      pid_trans_y:
        d: 0.0
        i: 0.0
        i_clamp: 0.0
        p: 4.0
      pid_trans_z:
        d: 0.0
        i: 0.0
        i_clamp: 0.0
        p: 4.0
      target_frame: arm_7_target
    joint_names:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - arm_6_joint
    - arm_7_joint
    root_frame: world
    twist_controller:
      controller_interface: cob_twist_controller/ControllerInterfaceJointStates
