/**:
  ros__parameters:
    DwaLocalPlannerROS:
      acc_lim_th: 1.5
      acc_lim_x: 0.8
      acc_lim_y: 0.0
      goal_distance_bias: 24.0
      max_vel_theta: 2.0
      max_vel_trans: 1.5
      max_vel_x: 1.5
      max_vel_y: 0.0
      meter_scoring: true
      min_vel_theta: 0.4
      min_vel_x: 0
      min_vel_y: 0.0
      occdist_scale: 0.01
      oscillation_reset_dist: 0.1
      publish_cost_grid: true
      scaling_speed: 1.0
      sim_granularity: 0.025
      sim_period: 0.1
      sim_time: 1.7
      theta_stopped_vel: 0.01
      trans_stopped_vel: 0.01
      vtheta_samples: 20
      vx_samples: 10
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.2
