/**:
  ros__parameters:
    TebLocalPlannerROS:
      acc_lim_theta: 0.5
      acc_lim_x: 0.8
      allow_init_with_backwards_motion: false
      exact_arc_length: false
      footprint_model:
        type: point
      global_plan_prune_distance: 1
      global_plan_viapoint_sep: -1
      max_samples: 500
      max_vel_theta: 2.0
      max_vel_x: 1.5
      max_vel_x_backwards: 0
      max_vel_y: 0.0
      min_turning_radius: 0.0
      publish_feedback: false
      yaw_goal_tolerance: 0.2
