/**:
  ros__parameters:
    defaults:
      steer_ctrl:
        d_phi_max: 12.0
        damp: 2.75
        dd_phi_max: 40.0
        spring: 15.0
        virt_mass: 0.1
      wheel_radius: 0.08
    type: cob_omni_drive_controller/WheelController
    wheels:
    - drive: fl_caster_r_wheel_joint
      steer: fl_caster_rotation_joint
      steer_neutral_position: -180.0
      x_pos: 0.368
    - drive: bl_caster_r_wheel_joint
      steer: bl_caster_rotation_joint
      steer_ctrl:
        dd_phi_max: 20.0
        virt_mass: 0.2
      steer_neutral_position: -180.0
    - drive: br_caster_r_wheel_joint
      steer: br_caster_rotation_joint
    - drive: fr_caster_r_wheel_joint
      steer: fr_caster_rotation_joint
      steer_drive_coupling: 0.5
