/**:
  ros__parameters:
    actuators:
      raw_data:
        absolute_encoder_position_port: act_abs_position
        current_limit_cmd_port: ref_limit_current
        effort_cmd_port: ref_current
        effort_port: act_current
        mode_cmd_port: ref_control_mode
        mode_port: act_control_mode
        position_cmd_port: ref_position
        position_port: act_position
        velocity_cmd_port: ref_velocity
    e_stop:
      raw_data:
        e_stop_port: emergency_stop_state
    joint_mode_black_list:
    - head_controller
    - torso_controller
    ros_control_component:
      ignore_read_errors: false
