robot_base_frame: $(arg frame)base_link

#https://github.com/inomuh/agv/blob/7c5e97311a77bd878fdaeba2b263bd6aa054db71/agv_navigation/params/agv_local.yaml
#https://github.com/inomuh/agv/blob/7c5e97311a77bd878fdaeba2b263bd6aa054db71/agv_navigation/params/agv_common.yaml

footprint: [[0.513, 0.364], [0.513, -0.364], [-0.513, -0.364], [-0.513, 0.364]]
footprint_padding: 0.01

robot_radius: 0.629
inscribed_radius: 0.629

observation_sources: scan
scan:
  {
    topic: $(arg namespace)/scan,
    sensor_frame: $(arg frame)scan_link,
    data_type: LaserScan,
    clearing: true,
    marking: true,
    inf_is_valid: true,
    max_obstacle_height: 2.0,
    min_obstacle_height: 0.0,
  }
