/**:
  ros__parameters:
    callbacks:
      periodic_eval:
        eval_freq: 10000
        max_num_moves_per_eps: 1250
        n_eval_episodes: 50
      stop_training:
        threshold: 0.98
        threshold_type: succ
      training_curriculum:
        curr_stage: 5
        lower_threshold: 0.65
        threshold_type: succ
        training_curriculum_file: semantic.yaml
        upper_threshold: 0.9
    debug_mode: true
    goal_radius: 0.25
    max_num_moves_per_eps: 50
    monitoring:
      cmd_line_logging:
        episode_statistics:
          enabled: true
          last_n_eps: 25
        training_metrics:
          enabled: true
      eval_log: false
      use_wandb: false
    n_envs: 1
    n_timesteps: 40000000
    no_gpu: false
    rl_agent:
      action_space:
        custom_discretization:
          buckets_angular_vel: 9
          buckets_linear_vel: 8
          enabled: true
        discrete: true
      architecture_name: RosnavResNet_5_norm
      checkpoint: best_model
      frame_stacking:
        enabled: false
        stack_size: 6
      laser:
        full_range_laser: true
        reduce_num_beams:
          enabled: false
          num_beams: 200
      lr_schedule:
        enabled: true
        settings:
          final_value: 0.0001
          initial_value: 0.001
        type: linear
      normalize:
        enabled: true
        settings:
          clip_obs: 30.0
          clip_reward: 20.0
          gamma: 0.99
          norm_obs: true
          norm_reward: false
      ppo:
        batch_size: 20480
        clip_range: 0.25
        ent_coef: 0.005
        gae_lambda: 0.95
        gamma: 0.99
        learning_rate: 0.0003
        m_batch_size: 512
        max_grad_norm: 0.5
        n_epochs: 3
        n_steps: 1200
        vf_coef: 0.22
      resume: jackal_RosnavResNet_5_norm_2024_03_23__21_02_24
      reward_fnc: base_semantic
      reward_fnc_kwargs:
        placeholder: 0
      subgoal_mode: false
    safety_distance: 0.5
    tm_modules: staged
    tm_obstacles: random
    tm_robots: random
